# Generated by Django 3.1.1 on 2020-09-30 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assesment', '0003_auto_20200930_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Temp',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
    ]
